# Generated by Django 4.1.7 on 2023-03-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_contact_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
