# Generated by Django 4.1.7 on 2023-03-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Skill name')),
                ('description', models.TextField(verbose_name='About skill')),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
