# Generated by Django 4.1.7 on 2023-03-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_recentwork_description_recentwork_upload_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webicon', models.FileField(blank=True, null=True, upload_to='home', verbose_name='WEB Icon')),
                ('homebg', models.ImageField(blank=True, null=True, upload_to='home', verbose_name='Home Background')),
                ('fb', models.FileField(blank=True, null=True, upload_to='home', verbose_name='FB Icon')),
                ('insta', models.FileField(blank=True, null=True, upload_to='home', verbose_name='Insta Icon')),
                ('twitter', models.FileField(blank=True, null=True, upload_to='home', verbose_name='Twitter Icon')),
                ('linkedin', models.FileField(blank=True, null=True, upload_to='home', verbose_name='Linkedin Icon')),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='cv',
            field=models.ImageField(blank=True, null=True, upload_to='about', verbose_name='CV'),
        ),
    ]
