# Generated by Django 4.1.7 on 2023-03-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_myicon_about_cv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myicon',
            options={'verbose_name': 'My Icon', 'verbose_name_plural': 'My Icon'},
        ),
    ]
