# Generated by Django 4.1.7 on 2023-04-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_myicon_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Coding Skill Name')),
                ('score', models.IntegerField(blank=True, default=80, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='skills')),
            ],
        ),
    ]
